\ProvidesClass{uebung}[2015/04/23 v0.1 Uebungsblaetterklasse von Sinan und Paul]
\LoadClass[10pt,a4paper]{article}
\usepackage[left=2.00cm, right=2.50cm, top=2.00cm, bottom=2.50cm]{geometry}
\usepackage[UTF8]{inputenc}
\usepackage{amsmath}
\usepackage{amsfonts}
\usepackage{amssymb}
\usepackage{mathtools}
\usepackage{wasysym}
\usepackage{graphicx}
\usepackage{paralist}
\usepackage{listings}


%NEUE Befehle
\newcommand{\qed}{\quad_\blacksquare}
\newcommand{\tick}{\quad\checkmark}

%List und Enumaration
\newcommand{\ls}{\begin{compactitem}}
\newcommand{\lsend}{\end{compactitem}}
\newcommand{\nm}{\begin{compactenum}}
\newcommand{\nmend}{\end{compactenum}}